services:
  - type: web
    name: sofo-changehub
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ffauweryjzpnskdaqcyp.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_bLkboY3aqcA-LRqg7VROgw_IjxTh84f
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_bLkboY3aqcA-LRqg7VROgw_IjxTh84f
      - key: SUPABASE_SCHEMA
        value: project_changehub
      - key: DATABASE_URL
        value: postgresql://postgres.ffauweryjzpnskdaqcyp:MrCoder%401304@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?options=-c%20search_path%3Dproject_changehub,public
