services:
  - type: web
    name: sofo-changehub
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://pjsofonic_db_user:MrCoder04%5D@sofo-change-hub.shztxpa.mongodb.net/sofo-change-hub?retryWrites=true&w=majority
